import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Loading1 from './components/Loading1'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-[40px] text-white">
          Loading Components
        </h1>
        <div className='flex flex-wrap justify-center items-center w-full mt-8'>
          <div className='w-60 h-60 border-2 rounded-xl m-16'>
            <Loading1/>
          </div>
          <div className='w-60 h-60 border-2 rounded-xl m-16'>
            <Loading1/>
          </div>
          <div className='w-60 h-60 border-2 rounded-xl m-16'>
            <Loading1/>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
